# example settings file
version: 1

jobs:
    myjob:
        path: .
        trigger: push
        branch: master
        runOnStart: true
        type: git
        command: dfdfdf d
        url: git@github.com:shukriadams/freeagent.git
        