# example settings file
version: 1

jobs:
    myjob:
        path: ./..
        trigger: push
        runOnStart: true
        type: git
        url: https://github.com/shukriadams/tuna-server.git
        